services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: dev_1234
      POSTGRES_DB: dev_db
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', 'dev_db', '-U', 'user']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5400:5432'
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: mydb
    volumes:
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - ./nest-cli.json:/app/nest-cli.json
      - ./node_modules:/app/node_modules
    depends_on:
      - db

volumes:
  dev_postgres_data:
